from enum import Enum


class AuditEventType(str, Enum):
    """Controlled security audit event types."""

    AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS"
    AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE"

    AUTHORIZATION_DENIED = "AUTHORIZATION_DENIED"

    POLICY_CREATED = "POLICY_CREATED"
    POLICY_UPDATED = "POLICY_UPDATED"
    POLICY_ENABLED = "POLICY_ENABLED"
    POLICY_DISABLED = "POLICY_DISABLED"
    POLICY_DELETED = "POLICY_DELETED"
    POLICY_VERSION_CREATED = "POLICY_VERSION_CREATED"
    POLICY_ROLLED_BACK = "POLICY_ROLLED_BACK"
    POLICY_CONFLICT = "POLICY_CONFLICT"

    POLICY_EVALUATED = "POLICY_EVALUATED"
    POLICY_SIMULATED = "POLICY_SIMULATED"

    INCIDENT_CREATED = "INCIDENT_CREATED"
    INCIDENT_ACKNOWLEDGED = "INCIDENT_ACKNOWLEDGED"
    INCIDENT_ASSIGNED = "INCIDENT_ASSIGNED"
    INCIDENT_STATUS_CHANGED = "INCIDENT_STATUS_CHANGED"
    INCIDENT_RESOLVED = "INCIDENT_RESOLVED"
    INCIDENT_DISMISSED = "INCIDENT_DISMISSED"
    INCIDENT_COMMENTED = "INCIDENT_COMMENTED"
    INCIDENT_REOPENED = "INCIDENT_REOPENED"
    INCIDENT_REMEDIATED = "INCIDENT_REMEDIATED"


class AuditOutcome(str, Enum):
    """Controlled outcomes for audit events."""

    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
    DENIED = "DENIED"
