import React, { useEffect, useState } from 'react';
import { evaluationApi } from '@/services/api/evaluationApi';
import { EvaluationResult } from '@/types/evaluation';
import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';
import { EmptyState } from '@/components/ui/EmptyState';
import { ErrorState } from '@/components/ui/ErrorState';
import { Skeleton } from '@/components/ui/Skeleton';
import {
  Activity,
  AlertTriangle,
  CheckCircle2,
  Clock,
  Globe,
  Info,
  Laptop,
  Lock,
  RefreshCw,
  Shield,
  ShieldAlert,
  UserCheck,
  Zap,
} from 'lucide-react';

export const RiskPage: React.FC = () => {
  const [evaluation, setEvaluation] = useState<EvaluationResult | null>(null);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  const fetchRiskAssessment = async () => {
    setLoading(true);
    setError(null);
    try {
      // Evaluate current user context against risk & policy engines
      const result = await evaluationApi.evaluateMe();
      setEvaluation(result);
    } catch (err: any) {
      setError(err.message || 'Failed to fetch current security risk evaluation.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchRiskAssessment();
  }, []);

  const getRiskBadgeVariant = (level?: string) => {
    switch (level?.toUpperCase()) {
      case 'LOW':
        return 'success';
      case 'MEDIUM':
        return 'warning';
      case 'HIGH':
        return 'danger';
      default:
        return 'outline';
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-slate-900 tracking-tight flex items-center gap-2">
            <Activity className="w-5 h-5 text-indigo-600" /> Security Signals & Risk Assessment
          </h2>
          <p className="text-xs text-slate-500 mt-1">
            Real-time security signal evaluation and risk scoring generated by Risk Evaluator
          </p>
        </div>
        <Button variant="outline" size="sm" onClick={fetchRiskAssessment} disabled={loading}>
          <RefreshCw className={`w-3.5 h-3.5 mr-1 ${loading ? 'animate-spin' : ''}`} /> Refresh Risk Profile
        </Button>
      </div>

      {loading ? (
        <div className="space-y-4">
          <Skeleton className="h-32 w-full" />
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Skeleton className="h-48 w-full" />
            <Skeleton className="h-48 w-full" />
          </div>
        </div>
      ) : error ? (
        <ErrorState title="Risk Evaluation Failed" message={error} onRetry={fetchRiskAssessment} />
      ) : !evaluation ? (
        <EmptyState
          title="No Risk Evaluation Available"
          description="Security context evaluation could not be completed."
          actionLabel="Re-evaluate"
          onAction={fetchRiskAssessment}
          icon={<ShieldAlert className="w-10 h-10 text-slate-400" />}
        />
      ) : (
        <>
          {/* Main Risk Overview Banner */}
          <Card className="border-l-4 border-l-indigo-600 overflow-hidden">
            <CardContent className="p-6">
              <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div className="space-y-2">
                  <div className="flex items-center gap-2">
                    <span className="text-xs font-semibold uppercase tracking-wider text-slate-500">
                      Overall Calculated Risk Level
                    </span>
                    <Badge variant={getRiskBadgeVariant(evaluation.risk_level ?? undefined)} className="text-xs px-2.5 py-0.5 font-bold">
                      {evaluation.risk_level || 'UNKNOWN'}
                    </Badge>
                  </div>
                  <h3 className="text-2xl font-black text-slate-900 tracking-tight">
                    {evaluation.risk_level === 'LOW' && 'Normal Security Posture'}
                    {evaluation.risk_level === 'MEDIUM' && 'Elevated Caution Posture'}
                    {evaluation.risk_level === 'HIGH' && 'High-Risk Posture — Additional Verification Required'}
                    {(!evaluation.risk_level || evaluation.risk_level === 'UNKNOWN') && 'Unknown Risk Profile'}
                  </h3>
                  <p className="text-xs text-slate-600 max-w-2xl leading-relaxed">
                    Evaluated at {new Date(evaluation.evaluated_at || Date.now()).toLocaleString()} • Correlation ID:{' '}
                    <span className="font-mono text-slate-800">{evaluation.correlation_id || 'N/A'}</span>
                  </p>
                </div>

                <div className="p-4 bg-slate-50 rounded-xl border border-slate-200 text-center min-w-[160px]">
                  <div className="text-[10px] uppercase font-bold text-slate-400 tracking-wider">
                    Policy Decision
                  </div>
                  <div
                    className={`text-lg font-black mt-1 ${
                      evaluation.decision === 'ALLOW'
                        ? 'text-emerald-600'
                        : evaluation.decision === 'MFA_REQUIRED'
                        ? 'text-amber-600'
                        : 'text-rose-600'
                    }`}
                  >
                    {evaluation.decision}
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Risk Factors Breakdown */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <Card className="lg:col-span-1">
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-bold flex items-center gap-2 text-slate-900">
                  <AlertTriangle className="w-4 h-4 text-amber-500" /> Contributor Risk Factors
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                {evaluation.risk_factors && evaluation.risk_factors.length > 0 ? (
                  evaluation.risk_factors.map((factor, idx) => (
                    <div
                      key={idx}
                      className="p-3 bg-amber-50/60 border border-amber-200/70 rounded-lg text-xs space-y-1"
                    >
                      <div className="font-semibold text-amber-900 flex items-center justify-between">
                        <span>{factor}</span>
                        <Badge variant="warning" className="text-[9px]">
                          FACTOR
                        </Badge>
                      </div>
                      <p className="text-[11px] text-amber-800/80">
                        Signal contribution flagged by risk engine evaluator rules.
                      </p>
                    </div>
                  ))
                ) : (
                  <div className="p-4 text-center bg-emerald-50/50 border border-emerald-200/60 rounded-lg text-xs text-emerald-800">
                    <CheckCircle2 className="w-5 h-5 mx-auto text-emerald-600 mb-1" />
                    No active high-severity risk factors detected.
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Evaluated Security Signals Grid */}
            <Card className="lg:col-span-2">
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-bold flex items-center gap-2 text-slate-900">
                  <Zap className="w-4 h-4 text-indigo-600" /> Contextual Security Signals
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  {evaluation.evaluated_signals && evaluation.evaluated_signals.length > 0 ? (
                    evaluation.evaluated_signals.map((sig, idx) => (
                      <div
                        key={idx}
                        className="p-3 bg-slate-50 border border-slate-200 rounded-lg text-xs space-y-1"
                      >
                        <div className="flex items-center justify-between">
                          <span className="font-semibold text-slate-900">{sig.name}</span>
                          <Badge variant="outline" className="text-[9px] font-mono">
                            {sig.confidence}
                          </Badge>
                        </div>
                        <div className="font-mono text-[11px] text-indigo-700 bg-white px-2 py-1 rounded border border-slate-200 truncate">
                          {String(sig.value ?? 'N/A')}
                        </div>
                        <div className="flex items-center justify-between text-[10px] text-slate-400">
                          <span>Src: {sig.source}</span>
                          <span>Status: {sig.status}</span>
                        </div>
                      </div>
                    ))
                  ) : (
                    <div className="col-span-2 p-4 text-center text-slate-500 italic text-xs">
                      No security signals returned from evaluation engine.
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          </div>
        </>
      )}
    </div>
  );
};
